In [1]:
from sklearn import datasets

In [2]:
iris= datasets.load_iris()
type(iris)

sklearn.utils.Bunch

iris는 데이터x를 딕셔너리로 가져오고, target이 y

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x=iris.data
y=iris.target
x.shape, y.shape, type(x),type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

category 가 몇개인지 확인하려고

넘파이의 유니크 사용할거얌

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape ,x_test.shape ,y_train.shape ,y_test.shape

((112, 4), (38, 4), (112,), (38,))

로짓에 담기 

In [7]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [8]:
log.fit(x_train, y_train)

LogisticRegression()

In [9]:
log.coef_, log.intercept_

(array([[-0.37527644,  0.82970081, -2.38195996, -0.94476496],
        [ 0.47979171, -0.1372575 , -0.20157486, -0.87193782],
        [-0.10451527, -0.6924433 ,  2.58353482,  1.81670278]]),
 array([  9.48187815,   1.70596913, -11.18784728]))

y=-0.39649966x +  0.76442637x + -2.32850292x + -0.94142027

In [19]:
log.predict_proba(x_train[100:104])

array([[9.89991717e-01, 1.00082725e-02, 1.07996466e-08],
       [3.28791229e-02, 9.14725112e-01, 5.23957649e-02],
       [2.62137136e-02, 9.09027842e-01, 6.47584446e-02],
       [1.25598812e-03, 2.13247448e-01, 7.85496564e-01]])

In [20]:
log.predict(x_train[100:104])

array([0, 1, 1, 2])

In [21]:
9.89991717e-01+ 1.00082725e-02+1.07996466e-08

1.0000000002996465

matrix 
판명하는 작업<br>평가부분 이벨류에이션 하기 

In [15]:
from sklearn import metrics

In [23]:
y_pred=log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

y_pred 와 y_train의 size가 같기 때문에 연산가능<br>
y_pred(모델 프레딕트한 값) 와 y_train(원래값) 을 비교해 맞은갯수 나옴<br>
그 맞는 갯수/전체갯수 하면 스코어가 나온다 <br>

In [24]:
y_pred

array([0, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 1,
       2, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 2, 2, 0, 2, 0,
       1, 0, 2, 2, 1, 0, 0, 2, 1, 0, 2, 2, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1,
       1, 0, 0, 0, 2, 2, 2, 1, 2, 1, 2, 2, 0, 2, 0, 1, 0, 1, 2, 1, 2, 2,
       2, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 0,
       0, 1])

In [25]:
y_train

array([0, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 1,
       2, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 0,
       1, 0, 2, 2, 1, 0, 0, 2, 1, 0, 2, 2, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1,
       1, 0, 0, 0, 2, 1, 2, 1, 2, 1, 2, 2, 0, 2, 0, 1, 0, 1, 2, 1, 2, 2,
       2, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 0,
       0, 1])

첫번째 논리<br>
accuracy부분을 체크하면됨

In [30]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.97      0.95      0.96        38
           2       0.95      0.97      0.96        39

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112

