In [1]:
from sklearn import datasets

In [2]:
iris= datasets.load_iris()
type(iris)

sklearn.utils.Bunch

iris는 데이터x를 딕셔너리로 가져오고, target이 y

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x=iris.data
y=iris.target
x.shape, y.shape, type(x),type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

category 가 몇개인지 확인하려고

넘파이의 유니크 사용할거얌

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

로짓에 담기 

In [8]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [9]:
log.fit(x_train, y_train)

LogisticRegression()

In [10]:
log.coef_, log.intercept_

(array([[-0.42576487,  0.8485574 , -2.39228456, -0.97140576],
        [ 0.4964269 , -0.1434329 , -0.178882  , -0.75956756],
        [-0.07066203, -0.7051245 ,  2.57116657,  1.73097332]]),
 array([  9.61889116,   1.47408566, -11.09297682]))

y=-0.39649966x +  0.76442637x + -2.32850292x + -0.94142027

In [11]:
log.predict_proba(x_train[100:104])

array([[1.24444886e-04, 1.68760721e-01, 8.31114834e-01],
       [9.77667652e-04, 2.41932572e-01, 7.57089760e-01],
       [3.11455427e-02, 9.44522933e-01, 2.43315246e-02],
       [2.54196992e-03, 8.70156287e-01, 1.27301743e-01]])

In [12]:
log.predict(x_train[100:104])

array([2, 2, 1, 1])

In [13]:
9.89991717e-01+ 1.00082725e-02+1.07996466e-08

1.0000000002996465

matrix 
판명하는 작업<br>평가부분 이벨류에이션 하기 

In [14]:
from sklearn import metrics

In [15]:
y_pred=log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

y_pred 와 y_train의 size가 같기 때문에 연산가능<br>
y_pred(모델 프레딕트한 값) 와 y_train(원래값) 을 비교해 맞은갯수 나옴<br>
그 맞는 갯수/전체갯수 하면 스코어가 나온다 <br>

In [16]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 1, 2, 2, 2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0,
       2, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 2, 2, 2, 1, 1, 1, 2, 2, 0, 1, 2,
       0, 2])

In [17]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 1, 2, 2, 2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0,
       2, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 2, 2, 2, 1, 1, 1, 2, 2, 0, 1, 1,
       0, 2])

accuracy 값쓸때 : 

f1-score 값쓸때 : 두 데이터를 trade-off 해서 값을 뽑음 ,대표하는 두개의 값을 조율한 가장 정확한 값(어느 한쪽으로 치우치지않음) 불균형 데이터에서 가장 잘 동작함

In [18]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.97      0.97      0.97        39
           2       0.97      0.97      0.97        37

    accuracy                           0.98       112
   macro avg       0.98      0.98      0.98       112
weighted avg       0.98      0.98      0.98       112



y_predict= 프리딕트한 카테고리 1행 1~3열 

y =카테고리값 1열 1~3행 

카테고리 1번이 True 인데 프레딕트가 False로 잡아낸게 2행3열부분

In [19]:
metrics.confusion_matrix(y_train, y_pred)

array([[36,  0,  0],
       [ 0, 38,  1],
       [ 0,  1, 36]], dtype=int64)